### ISSUE TITLE
Improve issue reporting from lookout messages

### ISSUE THREAD

**Issue by ajnavarro** [src-d/lookout#306]
In all lookout comments we can see a phrase like this one:

`If you have feedback about this comment, please, tell us.`

`tell us` is a link to a new issue on the analyzer repository. No context is provided on the issue by default.

My proposal is use `title` and `body` GET parameters to add automatically some information related with the analyzer comment. Example:

![lookout-issue](https://user-images.githubusercontent.com/1196465/46204514-c6b4b680-c31d-11e8-8bc8-9ce39be0db44.png)

Could generate the following link:

https://github.com/src-d/lookout-gometalint-analyzer/issues/new?title=[COMMENT%20ISSUE]%20seperate%20-%3E%20separate&body=-%20Action%0Aseperate%20typo%20to%20separate%0A-%20Problem%0A%3C!--%20please,%20describe%20here%20the%20problem%20you%20had%20--%3E

**Comment by dpordomingo** [comment]
That footer is built as it follows:
```go
fmt.Sprintf(providers.github.comment_footer, analyzer.feedback)
```
see docs at https://docs.sourced.tech/lookout/configuration#custom-footer.

Each analyzer defines its `feedback` (url) on their own ([examples](https://github.com/src-d/lookout/blob/master/.helm-staging.yml#L36)), so it can be an url to open a GitHub issue, a Bitbucket issue, a link to their docs, a link to an external site served by the analyzer and caring about feedback, a link to a certain Slack community...
so source{d} Lookout can not assume that footer link will open a GitHub issue.

One alternative to provide that useful behavior could be to let the analyzer to configure different ways to provide feedback, so source{d} Lookout could use different "stringer" depending on the method used.

example:
```yml
analyzers:
  - name: regular-analyzer
    addr: ipv4://lookout-style-analyzer:2000
    feedback: https://fancy-analyzer.com/feedback
  - name: fancy-analyzer
    addr: ipv4://lookout-gometalint-analyzer:10303
    github_issue: src-d/lookout-gometalint-analyzer
```
source{d} Lookout would work as it is currently doing for `regular-analyzer`, and it would link to a new issue into the repo identified by `github_issue` if it would exist.
