### ISSUE TITLE
Enhance comment footer on PR messages

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#472]
slightly related to https://github.com/src-d/lookout/issues/306 (same context)

Currently there is no an easy way to know where a lookout message come from, so different messages from different analyzers looks the same.

We could itterate a lot about it, like adding a picture of the analyzer, or different templates for them, but I think we're not there yet.

But we could, at least, identify the analyzer sending the message, using the footer on every comment posted by lookout.

**Comment by dpordomingo** [comment]
@se7entyse7en current footer comes from [provider/github/poster.go#L184](https://github.com/src-d/lookout/blob/master/provider/github/poster.go#L184)

**Comment by carlosms** [comment]
Maybe we can use a text template? I haven't tested anything, but I have in mind something like:
```yaml
providers:
  github:
    comment_footer: "_If you have any feedback for this comment made by the analyzer {{.Name}}, please, [tell us]({{.Feedback}})
```

This could be a base to build comments similar to the ones proposed in #306.
